### ISSUE TITLE
Using only http in Client.php

### ISSUE THREAD

**Issue by sioannides** [mac2000/woo-commerce-api-client#4]
What if I want to use https or use a port in my URL ($store_url)?

```
$options['base_url'] = ['http://' . parse_url($store_url, PHP_URL_HOST) . '/wc-api/{version}/', ['version' => 'v2']];
```

I think it should be something like:

```
$options['base_url'] = [$store_url . '/wc-api/{version}/', ['version' => 'v2']];
```

**Comment by marchenko1985** [comment]
seems reasonable, may you send pull request i will merge it

**Comment by sioannides** [comment]
@mac2000 You will make a new release for this?

**Comment by marchenko1985** [comment]
Done, thanks again for your contribution
